# GraphQL Type Definitions

# Enum for AttestationType
enum AttestationType {
  proposal
}

# scalar JSON
type CharmVerseCredential
  @createModel(accountRelation: LIST, description: "CharmVerse credentials issued using EAS")
  @createIndex(fields: [{ path: "timestamp" }])
  @createIndex(fields: [{ path: "issuer" }])
  @createIndex(fields: [{ path: "recipient" }])
  @createIndex(fields: [{ path: "schemaId" }])
  @createIndex(fields: [{ path: "type" }]) {
  author: DID! @documentAccount
  issuer: String! @string(maxLength: 42, minLength: 42)
  recipient: String! @string(maxLength: 42)
  content: String! @string(maxLength: 100000)
  sig: String! @string(maxLength: 100000)
  type: AttestationType!
  verificationUrl: String! @string(maxLength: 100000)
  chainId: Int!
  schemaId: String! @string(maxLength: 1000)
  timestamp: DateTime!
}
