# GraphQL Type Definitions

# scalar JSON
type CharmverseCredential
  @createModel(accountRelation: LIST, description: "CharmVerse credentials issued using EAS")
  @createIndex(fields: [{ path: "timestamp" }])
  @createIndex(fields: [{ path: "issuer" }])
  @createIndex(fields: [{ path: "recipient" }])
  @createIndex(fields: [{ path: "schemaId" }])
  @createIndex(fields: [{ path: "charmverseId" }])
  @createIndex(fields: [{ path: "type" }]) {
  author: DID! @documentAccount
  issuer: String! @string(maxLength: 100000, minLength: 1)
  recipient: String! @string(maxLength: 100000)
  content: String! @string(maxLength: 100000)
  sig: String! @string(maxLength: 100000)
  type: String! @string(maxLength: 100000)
  verificationUrl: String! @string(maxLength: 100000)
  chainId: Int!
  schemaId: String! @string(maxLength: 1000)
  timestamp: DateTime!
  charmverseId: String @string(maxLength: 1000)
}
