service: charmverse

frameworkVersion: '3'

# Create an optimized package for our functions
package:
  individually: true

plugins:
  # This plugins allows to use TS
  - serverless-esbuild
  # This plugins gives superpowers to serverless and allows us to deploy SQS queues easily
  - serverless-lift

custom:
  esbuild:
    watch:
      pattern: ['serverless/**/*.ts'] # match only typescript files in serverless directory

# This uses the lift plugin to generate our SQS setup in AWS
# Based on https://github.com/getlift/lift/blob/master/docs/queue.md
constructs:
  webhook-queue:
    type: queue
    # Setup the queue as FIFO (First in - First out queue)
    fifo: true
    # maxRetries: 5 <-- Adjust retries attempt if the job fails, default to 3
    worker:
      # Function responsible for handle messages in the queue
      handler: serverless/handler.webhookWorker
    extensions:
      queue:
        Properties:
          # Using predictable queue names, allows us to be consistent across every deployments
          # We can use branch names as stages, so each deployed env can have their own queue
          QueueName: charmverse-fifo-queue-${sls:stage}

provider:
  name: aws
  runtime: nodejs14.x
