import type { PageMeta } from '@charmverse/core/pages';
import type { Prisma } from '@charmverse/core/prisma';
import type { Page, PrismaTransactionClient } from '@charmverse/core/prisma-client';
import { prisma } from '@charmverse/core/prisma-client';
import { validate } from 'uuid';

export function pageMetaSelect(): Record<keyof PageMeta, true> {
  return {
    id: true,
    autoGenerated: true,
    boardId: true,
    bountyId: true,
    cardId: true,
    createdAt: true,
    createdBy: true,
    deletedAt: true,
    deletedBy: true,
    fullWidth: true,
    galleryImage: true,
    hasContent: true,
    headerImage: true,
    icon: true,
    index: true,
    isTemplate: true,
    parentId: true,
    path: true,
    additionalPaths: true,
    syncWithPageId: true,
    proposalId: true,
    title: true,
    spaceId: true,
    updatedAt: true,
    updatedBy: true,
    type: true,
    convertedProposalId: true
  };
}
