import type { Page } from '@charmverse/core/prisma';

import { InvalidInputError } from 'lib/utils/errors';

import { getRewardOrThrow } from './getReward';
import { getRewardErrors } from './getRewardErrors';
import { getRewardType } from './getRewardType';
import { updateRewardSettings, type UpdateableRewardFields } from './updateRewardSettings';

export type RewardPageProps = Partial<
  Pick<
    Page,
    'title' | 'content' | 'contentText' | 'sourceTemplateId' | 'headerImage' | 'icon' | 'type' | 'autoGenerated'
  >
>;

export type RewardPublishData = UpdateableRewardFields & {
  rewardId: string;
  pageProps?: RewardPageProps;
};

export async function publishReward(props: RewardPublishData) {
  const {
    rewardId,
    chainId = 1,
    rewardAmount,
    rewardToken,
    customReward = null,
    reviewers,
    pageProps,
    assignedSubmitters
  } = props;

  const rewardType = getRewardType({ rewardAmount, rewardToken, chainId, customReward });
  const errors = getRewardErrors({
    page: pageProps || null,
    reward: { assignedSubmitters, rewardAmount, rewardToken, chainId, customReward, reviewers },
    rewardType
  });
  if (errors.length > 0) {
    throw new InvalidInputError(errors.join(', '));
  }

  await updateRewardSettings({
    rewardId,
    updateContent: {
      ...props,
      rewardType
    }
  });

  const reward = await getRewardOrThrow({ rewardId });
  return reward;
}
