# GraphQL Type Definitions

# Enum for CredentialType
enum CredentialType {
  proposal
}

# scalar JSON

# This type comes from the @eas/sdk npm lib and is a raw signature that can be independently decoded and verified

type CredentialWallet {
  address: String! @string(maxLength: 42, minLength: 42)
  ensname: String @string(maxLength: 1000)
}

type SignedCredential
  @createModel(accountRelation: LIST, description: "A verifiable credential of type EIP712")
  @createIndex(fields: [{ path: "timestamp" }])
  @createIndex(fields: [{ path: "issuer" }])
  @createIndex(fields: [{ path: "recipient" }])
  @createIndex(fields: [{ path: "schemaId" }])
  @createIndex(fields: [{ path: "type" }]) {
  author: DID! @documentAccount
  issuer: String! @string(maxLength: 42, minlength: 42)
  recipient: String! @string(maxLength: 42)
  content: String! @string(maxLength: 100000)
  sig: String! @string(maxLength: 100000)
  type: CredentialType!
  verificationUrl: String! @string(maxLength: 100000)
  chainId: Int!
  schemaId: String! @string(maxLength: 1000)
  timestamp: Int!
}
