name: 'Build app'

inputs:
  app_name:
    description: The name of the app'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Restore build
      id: restore_build
      uses: actions/cache@v4
      with:
        # include the public folder in case the build output puts something there (like sw.js)
        path: |
          apps/${{ app_name }}/.next
          apps/${{ app_name }}/public
        key: app-${{ app_name }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('lib/**/*.ts[x]', '@connect-shared/**/*.ts[x]', 'apps/${{ app_name }}/**/*.ts', 'apps/${{ app_name }}/**/*.scss') }}

    - name: Build app
      shell: bash
      if: steps.restore_build.outputs.cache-hit != 'true'
      run: |
        npm run ${{ app_name }}:build