name: 'Deploy to production'
description: ''

inputs:
  app_name:
    description: 'The name of the app'
    required: true
  stack:
    description: 'The name of the CDK stack'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4.x
      with:
        short-length: 7

    # we need to bring back node_modules which includes tsconfig-paths which is used by CDK files
    - name: Install dependencies
      uses: ./.github/actions/install
      with:
        app_name: ${{ inputs.app_name }}

    - name: Setup cron config
      shell: bash
      # Note: "2>/dev/null || :" is a bash idiom that means "if the previous command fails, do nothing"
      run: |
        cp apps/${{ inputs.app_name }}/cron.yml cron.yaml 2>/dev/null || :

    - name: Set the docker compose env variables
      uses: mikefarah/yq@master
      with:
        cmd: |
          mv .ebextensions .ebextensions_tmp && mv .ebextensions_tmp/${{ inputs.app_name }} .ebextensions
          yq -I 4 -i '
            with(.option_settings."aws:elasticbeanstalk:application:environment";
                  .IMGTAG = "${{ github.run_id }}-${{ env.GITHUB_SHA_SHORT }}")
            ' .ebextensions/00_env_vars.config

    - name: Calculate Build ID
      shell: bash
      run: |
        build_id=${{ hashFiles('apps/${{ inputs.app_name }}/*.ts', 'apps/${{ inputs.app_name }}/*.tsx') }}
        echo "\nREACT_APP_BUILD_ID=$build_id" >> ./.ebstalk.apps.env/${{ inputs.app_name }}.env

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package and deploy
      shell: bash
      run: |
        cat files_to_zip.txt | zip --symlinks -r@ ${{ inputs.stack }}.zip
        npx aws-cdk deploy --method=direct -c name=${{ inputs.stack }}