name: 'Build connect'

runs:
  using: 'composite'
  steps:
    - name: Restore build
      id: restore_build
      uses: actions/cache@v4
      with:
        path: |
          apps/connect/.next
          apps/connect/public
          apps/sunnyawards/.next
        key: app-connect-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('lib/**/*.ts', '@connect-shared/**/*.ts[x]', 'apps/connect/**/*.ts[x]', 'apps/connect/**/*.scss', 'apps/sunnyawards/**/*.ts[x]', 'apps/sunnyawards/**/*.scss') }}

    - name: Build apps
      shell: bash
      if: steps.restore_build.outputs.cache-hit != 'true'
      run: |
        npm run connect:build
        npm run sunnyawards:build
