name: 'Install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Create .env.test.local file
      shell: bash
      run: cp .env.test.local.example .env.test.local

    - name: Cache dependencies
      id: cache_node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: nodemodules-cache-${{ hashFiles('package-lock.json') }}-${{ hashFiles('patches/**.patch', 'prisma/schema.prisma') }}

    - name: Install npm dependencies
      shell: bash
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      run: npm ci --no-audit --no-fund

    # Include this step to deploy and test a different branch of core
    - name: Install special core library
      shell: bash
      # 1. Set the webapp branch
      if: github.ref_name == 'page-views'
      # 2. Set core branch
      run: npm install github:charmverse/core#page-views
