name: 'Install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache dependencies
      id: cache_node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: nodemodules-cache-${{ hashFiles('package-lock.json') }}-${{ hashFiles('patches/**.patch', 'prisma/schema.prisma') }}

    - name: Install npm dependencies
      shell: bash
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      run: npm ci --no-audit --no-fund

    - name: Install CharmVerse core
      shell: bash
      run: npm install github:charmverse/common#ts-lib

    # Build prisma types which are cached inside of node_modules
    - name: Build Prisma types
      shell: bash
      run: npm run build:prisma
