name: 'Install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    ## Move to bottom after debug-----------
    - name: Install CharmVerse core
      shell: bash
      run: npm install github:charmverse/core#ts-lib

    - name: Copy prisma
      shell: bash
      run: npm run link:prisma

    - name: Debug prisma
      shell: bash
      run: ls -a && cd ./prisma && echo -e "\r\n----Prisma content" && ls -a && cd ../

    # Build prisma types which are cached inside of node_modules
    - name: Build Prisma types
      shell: bash
      run: npm run build:prisma

    ## Move to top after debug-----------

    - name: Cache dependencies
      id: cache_node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: nodemodules-cache-${{ hashFiles('package-lock.json') }}-${{ hashFiles('patches/**.patch', 'prisma/schema.prisma') }}

    - name: Install npm dependencies
      shell: bash
      if: steps.cache_node_modules.outputs.cache-hit != 'true'
      run: npm ci --no-audit --no-fund


