name: 'Build Docker Image'

inputs:
  codebase_sha:
    description: "Your code base sha, if it's different from the sha of the github action event"
    value: ""    
    required: false

outputs:
  full_image_name:
    description: "Full image repo and tag"
    value: "${{ steps.login-ecr.outputs.registry }}/charmverse-web3-workspace:${{ steps.prune_and_get_img_tag.outputs.img_tag }}"
  img_tag:
    description: "Image tag of the image"
    value: "${{ steps.prune_and_get_img_tag.outputs.img_tag }}"
  img_repo:
    description: "Image tag of the image"
    value: "${{ steps.login-ecr.outputs.registry }}/charmverse-web3-workspace"

runs:
  using: 'composite'
  steps:
    - name: Prune dev dependencies and calculate img tag
      id: prune_and_get_img_tag
      shell: bash
      run: |
        npm prune --production
        rm -rf .next/cache

        if [ -n "${{ inputs.codebase_sha }}" ]; then
          full_sha="${{ inputs.codebase_sha }}"
          echo "img_tag=${{ github.run_id }}-${full_sha:0:7}" >> $GITHUB_OUTPUT
        else
          echo "img_tag=${{ github.run_id }}-${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}
        mask-aws-account-id: 'false'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      uses: docker/build-push-action@v3
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPO: charmverse-web3-workspace
      with:
        context: .
        push: true
        tags: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ steps.prune_and_get_img_tag.outputs.img_tag }}'
        cache-from: type=gha
        cache-to: type=gha,mode=max
