name: 'Build Docker Image'

outputs:
  full_image_name:
    description: "Full image repo and tag"
    value: "${{ steps.login-ecr.outputs.registry }}/charmverse-web3-workspace:${{ github.run_id }}-${{ env.GITHUB_SHA_SHORT }}"
  img_tag:
    description: "Image tag of the image"
    value: "${{ github.run_id }}-${{ env.GITHUB_SHA_SHORT }}"
  img_repo:
    description: "Image tag of the image"
    value: "${{ steps.login-ecr.outputs.registry }}/charmverse-web3-workspace"

runs:
  using: 'composite'
  steps:
    - name: Remove dev dependencies
      shell: bash
      run: |
        npm prune --production
        rm -rf .next/cache

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      uses: docker/build-push-action@v3
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPO: charmverse-web3-workspace
      with:
        context: .
        push: true
        tags: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.run_id }}-${{ env.GITHUB_SHA_SHORT }}'
        cache-from: type=gha
        cache-to: type=gha,mode=max
