name: 'Deploy serverless to production'

on:
  push:
    branches: [main]
    paths:
      # Trigger the job only when the serverless config or files have been changed
      - serverless/**
      - serverless.yml

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function_name: ["webhook-queueWorker", "webhookChecker"]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: serverless deploy ${{ matrix.function_name }}
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage prod --function ${{ matrix.function_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
